### ISSUE TITLE
Всё почти прекрасно 👌

### ISSUE THREAD

**Issue by trendoman** [dotland/mnemonic-kb-ru#3]
Не было ли желания добавить еще элементов для гитхаба — например, прямых кавычек и обратного апострофа?

**Comment by dotland** [comment]
Спасибо за предложение, [прямых кавычек](https://symbl.cc/ru/0027/) действительно нет в этом клавиатуре. [Латинский гравис](https://symbl.cc/ru/0060/) можно вводить с помощью `AltGr`+`՝`+`՝`. Нет и  [прямых двойных кавычек](https://symbl.cc/en/0022/) в этом клавиатуре: клавиша слево от `Enter` вводит ь, Ь и комбинируемые ударения. Для одинарных и двойных кавычек необходимо переключаться на английкую клавиатуру, и использовать клавишу слево от `Enter`, думаю так легче будет запомнить.

**Comment by dotland** [comment]
Исправлено в версии v1.0.1.
* Латинский гравис — `AltGr`+`՝`
* Одинарная кавычка — `AltGr`+`'`
* Двойная кавычка — `AltGr`+`Shift`+`'`
* Комбинируемый акут — `AltGr`+`/`
* Комбинируемый гравис — `AltGr`+`\`
